### ISSUE TITLE
Error generating aliases in Edge 115

### ISSUE THREAD

**Issue by einsq** [jonerrr/mailcow-alias-extension#3]
![Error generating alias](https://github.com/jonerrr/mailcow-alias-extension/assets/76105404/3b961815-8e54-4e9b-85f1-f8abf7b701a6)
![Einstellungen](https://github.com/jonerrr/mailcow-alias-extension/assets/76105404/6669603b-2bf4-4c53-9638-541a603e41ad)

Extension works fine in FF, installed it in Edge. Configuration is ok, getting an alias E-Mail in this menu. But no alias is generated in normal mode.

**Comment by jonerrr** [comment]
Thank you for using the extension. I haven't tested Edge but I found a similar bug when using Chrome. I think the issue is that it's not possible to copy stuff to the clipboard because of Manifest V3. I think it is possible to clone the repo, compile a MV2 version, and install that. I am currently not home but when I get back I will try to fix the issue.

**Comment by einsq** [comment]
In my understanding, your extension should generate and listing aliases that are transfered to mailcow. The transfer of the examples to the list in mailcow works in FF. But not in the edge extension.

**Comment by jonerrr** [comment]
I redesigned how the alias emails are copied to the clipboard. It should now work in Chrome and Edge (I have not tested Edge yet but it's based on Chromium so it should work).
Once the update is approved by the Chrome store, aliases will be created by right-clicking anywhere on the webpage and selecting the "Generate Alias" option.

If this is still an issue once you get the update, please let me know.
