### ISSUE TITLE
Add comment when creating alias

### ISSUE THREAD

**Issue by Antoineb2s** [jonerrr/mailcow-alias-extension#5]
Hi,

Nice job !

Is it possible to add a comment (for example the 'private comment') when creating alias ?
It could be nice to see for what website the alias should be used. I guess website name could be get automaticaly in order to fill up this comment field as well !

Thanks !

**Comment by jonerrr** [comment]
Currently, I am adding a comment that includes the hash of the URL. I think I will change that to just be unhashed.

**Comment by Antoineb2s** [comment]
Hello, thanks.

Private comment field is not showed up, should be great :)

![image](https://github.com/jonerrr/mailcow-alias-extension/assets/16756375/25f99816-e60f-48a4-b6c2-c958eb90930d)

Also, when clicking on mailcow aliases, it could be interesting to show all aliases (for the specified target) not only the ones your extension have created.

**Comment by jonerrr** [comment]
Sorry for the confusion. I added the hostname to the private comment but it is only viewable on the mailcow website. I have switched from using Mailcow to Fastmail so I haven't made too many changes to the extension.

The reason I don't show all the aliases in mailcow is because I use the private comment to store specific metadata that the extension uses. I was thinking about displaying aliases for the current domain at the top but I haven't had the time to add that. 

If you'd like to add a private comment column and other features, you're welcome to make a PR.
